language: python
compiler: gcc

python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"

install:
  - pip install -r requirements.txt
  - wget https://github.com/google/protobuf/releases/download/v3.4.0/protoc-3.4.0-linux-x86_64.zip
  - unzip protoc-3.4.0-linux-x86_64.zip -d protoc-3.4.0-linux-x86_64
  - protoc-3.4.0-linux-x86_64/bin/protoc --python_out=. *.proto

script:
  - pytest --cov=./

after_success:
  - codecov
